In [3]:
import pandas as pd
from sqlalchemy import create_engine

In [21]:
# READ THE CSV BACK 
df_loaded = pd.read_csv('fintech_sentiment_analysis_results_2.csv')

print(f"✓ Loaded {len(df_loaded)} rows")
print(f"\nColumn names: {list(df_loaded.columns)}")
print(f"\nData types:\n{df_loaded.dtypes}")
print(f"\nFirst 3 rows:")
df_loaded.head(3)

✓ Loaded 1267 rows

Column names: ['bank_name', 'app_name', 'review_id', 'bank_id', 'review_text', 'rating', 'review_date', 'sentiment_label', 'sentiment_score', 'identified_theme', 'source']

Data types:
bank_name               str
app_name                str
review_id             int64
bank_id                 str
review_text             str
rating                int64
review_date             str
sentiment_label         str
sentiment_score     float64
identified_theme        str
source                  str
dtype: object

First 3 rows:

,bank_name,app_name,review_id,bank_id,review_text,rating,review_date,sentiment_label,sentiment_score,identified_theme,source
0,Cbe,Cbe Mobile App,0,CBE_APP_ID,worst,1,2026-05-16,NEGATIVE,-0.999802,Other,Google Play Store
1,Cbe,Cbe Mobile App,1,CBE_APP_ID,this app very full,5,2026-05-16,POSITIVE,0.997449,Other,Google Play Store
2,Cbe,Cbe Mobile App,2,CBE_APP_ID,good apps,4,2026-05-16,POSITIVE,0.999861,POSITIVE,Google Play Store

In [22]:
username = "postgres"
password = "123"
host = "localhost"
port = "5432"
database = "bank_reviews"

engine = create_engine(
    f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}"
)

print("Connected successfully!")

Connected successfully!

In [23]:
banks_df = df_loaded[['bank_name', 'app_name']].drop_duplicates()

banks_df.to_sql(
    'banks',
    engine,
    if_exists='append',
    index=False
)

print("Banks inserted!")

Banks inserted!

In [24]:
banks = pd.read_sql("SELECT * FROM banks", engine)

banks.head()

   bank_id bank_name           app_name
0        1       Cbe     Cbe Mobile App
1        2    Dashen  Dashen Mobile App
2        3       Boa     Boa Mobile App

In [28]:
reviews_df = df_loaded[[
    'bank_id',
    'review_text',
    'rating',
    'review_date',
    'sentiment_label',
    'sentiment_score',
    'identified_theme',
    'source'
]]

In [29]:
reviews_df.to_sql(
    'reviews',
    engine,
    if_exists='append',
    index=False
)

print("Reviews inserted!")

Reviews inserted!